apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftpgo
  labels:
    app: sftpgo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sftpgo
  template:
    metadata:
      labels:
        app: sftpgo
    spec:
      containers:
        - name: sftpgo
          image: drakkan/sftpgo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: sftp
              containerPort: 2022
            - name: web
              containerPort: 8080
          env:
            - name: SFTPGO_HTTPD_BINDINGS__0__PORT
              value: "8080"
            - name: SFTPGO_DATA_PROVIDER__DRIVER
              value: "sqlite"
            - name: SFTPGO_COMMON__UPLOAD_MODE
              value: "AUTO"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: sftpgo-lb
  labels:
    app: sftpgo
spec:
  type: LoadBalancer
  selector:
    app: sftpgo
  ports:
    - name: sftp
      port: 22
      targetPort: 2022
      protocol: TCP
    - name: web
      port: 8080
      targetPort: 8080
      protocol: TCP
